### ISSUE TITLE
No checking cell data in Limit Order mint transaction

### ISSUE THREAD

**Issue by XuJiandong** [ickb/proposal#11]
```
Outputs:
    - Limit Order cell:
        Data:
            - Amount (16 bytes),
            - MintOrderData variant of OrderData
        Type: xUDT
        Lock: Limit Order role
            CodeHash: Limit Order Hash
            HashType: Data1
            Args: Empty
```
This output part `MintOrderData variant of OrderData` can be replaced by `MatchOrderData`.

**Comment by phroi** [comment]
Hey @XuJiandong, thank you for publicly expressing your interest in iCKB by reviewing the proposal, I personally appreciate a lot!! 🙏

Limit Order's `Mint` in the proposal does not explicitly document that only `MintOrderData` variant of `OrderData` is valid. Good catch!!

**Comment by XuJiandong** [comment]
From the code:
https://github.com/ickb/v1-core/blob/29170d139f6c320fe2588131f124f8de788dd50a/scripts/contracts/limit_order/src/entry.rs#L180-L184

"Match" order is allowed here.

**Comment by phroi** [comment]
And later on is restricted [here](https://github.com/ickb/v1-core/blob/29170d139f6c320fe2588131f124f8de788dd50a/scripts/contracts/limit_order/src/entry.rs#L62C1-L81C6):

```rust
    // Validate actions
    for [Order {
        data: in_maybe_data,
        has_master: in_has_master,
    }, Order {
        data: out_maybe_data,
        has_master: out_has_master,
    }] in metapoint_2_order.into_values()
    {
        match (in_maybe_data, in_has_master, out_maybe_data, out_has_master) {
            // Mint Order
            (None, false, Some(_), true) => (),
            // Melt Order
            (Some(_), true, None, false) => (),
            // Match Order
            (Some(i), false, Some(o), false) => validate(i, o)?,
            // Every other configuration is invalid
            _ => return Err(Error::InvalidConfiguration),
        }
    }
```
If `Some(_)` in `(None, false, Some(_), true) => (),` was a Match order in output, it would not be able to reference its master cell in output (due to the information memorized in each of the `OrderData` variants) and it would error out with `InvalidConfiguration`.

@XuJiandong does all this make sense?

**Comment by XuJiandong** [comment]
Assume the following is a valid cell:

```
Outputs:
    - Limit Order cell:
        Data:
            - Amount (16 bytes),
            - MintOrderData variant of OrderData
        Type: xUDT
        Lock: Limit Order role
            CodeHash: Limit Order Hash
            HashType: Data1
            Args: Empty
```

The `MintOrderData variant of OrderData` can be replaced(action from `mint` to `match`, and with other parts updated), and the cell will still remain valid.

**Comment by phroi** [comment]
> Assume the following is a valid cell

That's the issue, assuming that:
- this cell is the only one in output
- it's a Mint Action

Then it's an **invalid cell**.

The transaction may still validate for the the technical reason that output locks do not run. Then again if Limit Order Script validate that transaction even a single time (for example a Melt also happening in the same tx input), then the transaction will not validate, because indeed a Minting an order without its Master cell is not allowed. (See the code from the earlier comment)

**Comment by XuJiandong** [comment]
In this example below(from document):
```
CellDeps:
    - Limit Order data cell
    - ...
Inputs:
    - ...
Outputs:
    - Limit Order cell:
        Data:
            - Amount (16 bytes),
            - MintOrderData variant of OrderData
        Type: xUDT
        Lock: Limit Order role
            CodeHash: Limit Order Hash
            HashType: Data1
            Args: Empty
    - Master cell:
        Data: ...
        Type: Master role
            CodeHash: Limit Order Hash
            HashType: Data1
            Args: Empty
        Lock: A lock that identifies the user
```

The MintOrderData variant of OrderData can be replaced(action from mint to match, and with other parts updated), and the cell will still remain valid.
