### ISSUE TITLE
Block rollback issue

### ISSUE THREAD

**Issue by msjyryxdzzj** [ickb/proposal#15]
For deposit does it take into account the case of block rollback on the ckb chain? Because does the first step of deposit throw an exception if the block is rolled back?
![QQ_1725447244592](https://github.com/user-attachments/assets/573b7e8c-0ab0-4701-bd79-9390c26ae867)

**Comment by phroi** [comment]
Hey @msjyryxdzzj, thank you for publicly expressing your interest in iCKB by auditing the proposal and L1 scripts source code as part of the Scalebit external audit, I personally appreciate a lot!! 🙏

I would kindly request you and the full Scalebit audit team to use Github links to point out exactly which part of the proposal you would like to review in each occasion (specific commit + specific headings), like the following: https://github.com/ickb/proposal/tree/e10a8e8fcacb2a7d52b04c65c4222a0f79055c1e#deposit-phase-2

And the quoting the specific example you would like to review:

```yaml
CellDeps:
    - iCKB Dep Group cell # <-- ROLLBACK?!?!?!?!?!
    - ...
HeaderDeps: 
    - Deposit block
    - ...
Inputs:
    - Receipt:
        Data: ReceiptData
        Type:
            CodeHash: iCKB Logic Hash
            HashType: Data1
            Args: Empty
        Lock: A lock that identifies the user
    - ...
Outputs:
    - Token:
        Data: amount (16 bytes)
        Type:
            CodeHash: Standard xUDT Script
            HashType: Data1
            Args: [iCKB Logic Script Hash, 0x80000000]
        Lock: A lock that identifies the user
```

It's really easy, try it out!! :hugs:

That said, this is an interesting hypothetical failure mode, pretty neat, keep this kind of issues coming!!

> For deposit does it take into account the case of block rollback on the ckb chain? Because does the first step of deposit throw an exception if the block is rolled back?

Both deposit phase 1 and deposit phase 2 are on-chain and on the same chain (Nevos L1). If deposit block (header) is not on-chain (possibly due to a re-org), then the transaction cannot be added to the chain. [From the Transaction Structure RFC](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0022-transaction-structure/0022-transaction-structure.md#header-deps):
> Header Deps allows the scripts to read a block header which hashes are listed in `header_deps`. There's another precondition that the transaction can only be added to the chain if all the block listed in `header_deps` are already in the chain

Don't trust me or the RFC, feel free to test it out with a transaction 🤗

@msjyryxdzzj does it all this make sense?

Love & Peace, Phroi
