### ISSUE TITLE
Attack on iCKB Deposit Pool to reset interests and maturity time

### ISSUE THREAD

**Issue by msjyryxdzzj** [ickb/proposal#18]
After I read through the ickb logic code, I constructed the following transaction for the attack:（Let's assume that the ickb/ckb exchange rate is 1:1 (which would have no effect on the attack).）
```java=
CellDeps:
    - iCKB Dep Group cell
    - ...
HeaderDeps: 
    - Deposit Block Header Hash
    - ...
Inputs:
    - Nervos DAO deposit cell with iCKB Logic Script:  (unused_capacity=8000)
        Data: 8 bytes filled with zeros
        Type: Nervos DAO
        Lock:
            CodeHash: iCKB Logic Hash
            HashType: Data1
            Args: Empty
    - Token:
        Data: amount (16 bytes) (amount = 8000)
        Type:
            CodeHash: Standard xUDT Script
            HashType: Data1
            Args: [iCKB Logic Script Hash, 0x80000000]
        Lock: A lock that identifies the user
    - ...
Outputs:
    - Nervos DAO phase 1 withdrawal cell: (unused_capacity=8000)
        Data: 8 bytes filled with zeros
        Type: Nervos DAO
        Lock:
            CodeHash: iCKB Logic Hash
            HashType: Data1
            Args: Empty
    - ...
    - Receipt:
        Data: ReceiptData
            deposit_quantity: Quantity of deposits (4 bytes) (DQ = 1)
            deposit_amount: Single deposit unoccupied capacity (8 bytes) (DA = 8000)
        Type:
            CodeHash: iCKB Logic Hash
            HashType: Data1
            Args: Empty
        Lock: A lock that identifies the user
```
This transaction uses deposit phase 1 and withdrawal phase 1 together, I also briefly read the code of the nervos DAO and found that there is no check for output in the nervos DAO to prevent such problems, and this transaction will pass. (I did not actually test this, but just constructed the transaction for this attack during the audit.) This attack can cause the attacker can dos ickb all deposit orders, can be in the transaction fee for the cost of arbitrarily modify the deposit start time, I think it is a very serious problem.
Suggestion for fix: add a check for deposit cells with ickb lock scripts in the input cell that should not contain deposit cells in the out put.

**Comment by phroi** [comment]
Hey @msjyryxdzzj, thank you for publicly expressing your interest in iCKB by auditing the proposal and L1 scripts source code as part of the Scalebit external audit, I personally appreciate a lot!! 🙏

Your comment follows these assumptions:

- AR doesn't change, so time has stopped at genesis block.
- Due to the previous assumption, the exchange rate is constant at 1 CKB = 1 iCKB

Let me start by pointing out a few things on the proposed transaction.

### How can you be sure that deposit of exactly 8000 CKB exists?

```yaml
Inputs:
    - Nervos DAO deposit cell with iCKB Logic Script:  (unused_capacity=8000)
```

It would be unlikely that such deposit exists as [a user creating it would lose 82 CKB in unaccounted unoccupied capacity](https://github.com/ickb/proposal?tab=readme-ov-file#deposit-phase-1) by design, around 1% of the deposited amount.

**Side Note about `lose 82 CKB`**: If the user user creates the deposit and right after he withdraws from it, nothing is lost. Then again if someone else use that deposit to withdraw, then those 82 CKB are lost forever to the user who created the deposit. This is by design to incentivize [standard deposits](https://github.com/ickb/proposal?#standard-deposit).

Let's use a realistically sized deposit with unoccupied capacity of 100k iCKB (= 100k unoccupied CKB, under current assumptions)

### Is it a deposit or a withdrawal request in output?

```yaml
Outputs:
    - Nervos DAO phase 1 withdrawal cell: (unused_capacity=8000)
        Data: 8 bytes filled with zeros
```

From the data it is a deposit, but from the description it's a withdrawal request.

> This transaction uses deposit phase 1 and withdrawal phase 1 together

I guess that you wanted to put both, maybe forgot about one? 🤔

> no check for output in the nervos DAO to prevent such problems

Trying to request the withdrawal of a deposit into another deposit would fail the [following rule](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0023-dao-deposit-withdraw/0023-dao-deposit-withdraw.md#withdraw-phase-1):

> For a `deposit cell` at input index `i`, a `withdrawing cell` MUST be created at output index `i` with the following requirements:
>    - [...]
>    - The `withdrawing cell` MUST also have 8 bytes length cell data, but instead of 8 zero, it MUST store the block number of the `deposit cell`'s including block. The number MUST be packed in 64-bit unsigned little-endian integer format.

And yes, [this is checked in the NervosDAO implementation](https://github.com/nervosnetwork/ckb-system-scripts/blob/f25c5ae8824c4907ad94326a0113a03defab9bfc/c/dao.c#L362-L364).


## Revised Attack

```yaml
CellDeps:
    - iCKB Dep Group cell
    - ...
HeaderDeps: 
    - Deposit Block Header Hash of A)
    - Receipt Block Header Hash of B)
    - ...
Inputs:
    - A) Nervos DAO deposit cell with iCKB Logic Script: (unused_capacity=100k CKB, worth 100k iCKB)
        Data: 8 bytes filled with zeros
        Type: Nervos DAO
        Lock:
            CodeHash: iCKB Logic Hash
            HashType: Data1
            Args: Empty
    - B) Receipt:
        Data: ReceiptData  (amount=100k CKB, worth 100k iCKB)
            deposit_quantity: Quantity of deposits (4 bytes) (DQ = 1)
            deposit_amount: Single deposit unoccupied capacity (8 bytes) (DA = 100k CKB)
        Type:
            CodeHash: iCKB Logic Hash
            HashType: Data1
            Args: Empty
        Lock: A lock that identifies the user
    - ...
Outputs:
    - Nervos DAO phase 1 withdrawal cell: (unused_capacity=100k CKB, worth 100k iCKB)
        Data: Deposit cell's including block number
        Type: Nervos DAO
        Lock: A lock that identifies the user
    Outputs:
    - Nervos DAO deposit cell with iCKB Logic Lock: (unused_capacity=100k CKB, worth 100k iCKB)
        Data: 8 bytes filled with zeros
        Type: Nervos DAO
        Lock:
            CodeHash: iCKB Logic Hash
            HashType: Data1
            Args: Empty
    - Receipt:
        Data: ReceiptData (amount=100k CKB, worth 100k iCKB)
            deposit_quantity: Quantity of deposits (4 bytes) (DQ = 1)
            deposit_amount: Single deposit unoccupied capacity (8 bytes) (DA = 100k CKB)
        Type:
            CodeHash: iCKB Logic Hash
            HashType: Data1
            Args: Empty
        Lock: A lock that identifies the user
    - ...
```

## Where the additional 100k CKB for the second deposit come from?

Excluding tx fees and CKB needed for state rent, the attacker could have a capital of 200k CKB and once the Withdrawal Request  is ready ([yes, there is a wait time in NervosDAO withdrawal process](https://www.nervos.org/knowledge-base/nervosdao_withdrawal_process_explained)), you can attack with the second deposit. So alternating the two deposits in the attack.

## Discussion

> This attack can cause the attacker can dos ickb all deposit orders, can be in the transaction fee for the cost of arbitrarily modify the deposit start time, I think it is a very serious problem.

Not really, once you factor in that the attacker has to wait for Withdrawal Request to mature, this attack seems to have a limited reach.

All in all, this attack seems a variant of [the Busiwork Attack, which I already documented (and asked to review)](https://github.com/ickb/proposal/issues/8). If the Busiwork Attack is the underlying idea behind this attack, feel free to continue to this discussion there!

> Suggestion for fix: add a check for deposit cells with ickb lock scripts in the input cell that should not contain deposit cells in the out put.

While this suggestion is indeed reasonable, it doesn't really solve a particular problem.

Also it could create future issues: say come to pass a future where users create partial iCKB transactions and then an aggregator put them together in the final tx, your additional check would create issues if a user wanted to deposit while the other one wanted to withdraw.

@msjyryxdzzj does all this seem reasonable?
