### ISSUE TITLE
Clarify the OTX scenario

### ISSUE THREAD

**Issue by XuJiandong** [ickb/proposal#3]
Firstly, this assumption is questionable:

> Let's assume that:
> * The user lock is OTX signature based.
> * The user unlocks some cells with signature in an OTX transaction, first OTX.

Since there is no OTX implementation in the real world, this design introduces unnecessary complexity.

**Comment by phroi** [comment]
> Firstly, this assumption is questionable:

Agreed, also @xxuejie said something around these lines somewhere in [our small discussion](https://talk.nervos.org/t/ickb-journey-into-cobuild/7918).

> Since there is no OTX implementation in the real world, this design introduces unnecessary complexity.

Also can you assure me that from now until the end of time no such OTX design will exist? (No)

@XuJiandong could you show how this introduces unnecessary complexity by providing a less complex solution?

**Comment by XuJiandong** [comment]
In withdraw phanse 1
```
Inputs:
    - Nervos DAO deposit cell with iCKB Logic Script:
        Data: 8 bytes filled with zeros
        Type: Nervos DAO
        Lock:
            CodeHash: iCKB Logic Type ID
            HashType: Type
            Args: Empty
    - Token:
        Data: amount (16 bytes)
        Type:
            CodeHash: Standard xUDT Script
            HashType: Data1
            Args: [iCKB Logic Type ID, 0x80000000]
        Lock: A lock that identifies the user
    - ...
Outputs:
    - Nervos DAO phase 1 withdrawal cell:
        Data: Deposit cell's including block number
        Type: Nervos DAO
        Lock: A lock that identifies the user
    - ...
 ```
`a lock that identifies the user`, the user can be the withdrawer directly.
