### ISSUE TITLE
Substitute cell in step "Melt Owned Owner"

### ISSUE THREAD

**Issue by XuJiandong** [ickb/proposal#6]
```
CellDeps:
    - iCKB Dep Group cell
    - Owned Owner data cell
    - ...
HeaderDeps: 
    - Deposit block
    - ...
Inputs:
    - Nervos DAO phase 1 withdrawal cell:
        Data: Deposit cell's including block number
        Type: Nervos DAO
        Lock: Owned role
            CodeHash: Owned Owner Type ID
            HashType: Type
            Args: Empty
    - Owner cell:
        Data: Signed distance from Owned cell (4 bytes)
        Type: Owner role
            CodeHash: Owned Owner Type ID
            HashType: Type
            Args: Empty
        Lock: A lock that identifies the user
    - ...
Outputs:
    - ...
    -
```
In the step above, what if the "owner cell" is replaced by pre-made cell with different lock?
