### ISSUE TITLE
Typo in `Example of Limit Order mint`

### ISSUE THREAD

**Issue by XuJiandong** [ickb/proposal#9]
```
CellDeps:
    - Limit Order data cell
    - ...
Inputs:
    - ...
Outputs:
    - Limit Order cell:
        Data:
            - Amount (16 bytes),
            - MintOrderData variant of OrderData
        Type: xUDT
        Lock: Limit Order role
            CodeHash: Limit Order Hash
            HashType: Data1
            Args: Empty
    - Master cell:
        Data: ...
        Lock: Master role
            CodeHash: Limit Order Hash
            HashType: Data1
            Args: Empty
        Lock: A lock that identifies the user
```
` Lock: Master role` -> ` Type: Master role`
